name: 'Keel Dockerfile Linter'
description: 'Lint and format Dockerfiles for security, performance, and best practices'
author: 'HueCodes'

branding:
  icon: 'anchor'
  color: 'blue'

inputs:
  path:
    description: 'Path to Dockerfile(s). Supports glob patterns.'
    required: false
    default: 'Dockerfile'

  fail-on-severity:
    description: 'Minimum severity to cause failure (error|warning|info|hint)'
    required: false
    default: 'warning'

  output-format:
    description: 'Output format (terminal|json|sarif|github)'
    required: false
    default: 'github'

  auto-fix:
    description: 'Automatically fix issues where possible'
    required: false
    default: 'false'

  check-format:
    description: 'Check if Dockerfiles are formatted (fail if not)'
    required: false
    default: 'false'

  ignore:
    description: 'Comma-separated list of rule IDs to ignore'
    required: false
    default: ''

  only:
    description: 'Comma-separated list of rule IDs to run exclusively'
    required: false
    default: ''

  version:
    description: 'Version of keel to use (default: latest)'
    required: false
    default: 'latest'

outputs:
  issues-found:
    description: 'Number of issues found'
    value: ${{ steps.lint.outputs.issues-found }}

  has-errors:
    description: 'Whether error-level issues were found'
    value: ${{ steps.lint.outputs.has-errors }}

runs:
  using: 'composite'
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Install keel
      shell: bash
      run: |
        if [ "${{ inputs.version }}" = "latest" ]; then
          go install github.com/HueCodes/keel/cmd/keel@latest
        else
          go install github.com/HueCodes/keel/cmd/keel@${{ inputs.version }}
        fi

    - name: Check formatting
      if: inputs.check-format == 'true'
      shell: bash
      run: |
        EXIT_CODE=0
        for dockerfile in ${{ inputs.path }}; do
          if [ -f "$dockerfile" ]; then
            keel fmt --check "$dockerfile" || {
              echo "::error file=$dockerfile::Dockerfile is not formatted. Run 'keel fmt -w $dockerfile'"
              EXIT_CODE=1
            }
          fi
        done
        exit $EXIT_CODE

    - name: Auto-fix issues
      if: inputs.auto-fix == 'true'
      shell: bash
      run: |
        for dockerfile in ${{ inputs.path }}; do
          if [ -f "$dockerfile" ]; then
            keel fix -w "$dockerfile"
          fi
        done

    - name: Lint Dockerfiles
      id: lint
      shell: bash
      run: |
        ARGS=""

        # Add severity flag
        if [ -n "${{ inputs.fail-on-severity }}" ]; then
          ARGS="$ARGS --severity ${{ inputs.fail-on-severity }}"
        fi

        # Add output format
        ARGS="$ARGS --output ${{ inputs.output-format }}"

        # Add ignore rules
        if [ -n "${{ inputs.ignore }}" ]; then
          ARGS="$ARGS --ignore ${{ inputs.ignore }}"
        fi

        # Add only rules
        if [ -n "${{ inputs.only }}" ]; then
          ARGS="$ARGS --only ${{ inputs.only }}"
        fi

        ISSUES=0
        HAS_ERRORS=false

        for dockerfile in ${{ inputs.path }}; do
          if [ -f "$dockerfile" ]; then
            if ! keel lint $ARGS "$dockerfile"; then
              ISSUES=$((ISSUES + 1))
              HAS_ERRORS=true
            fi
          fi
        done

        echo "issues-found=$ISSUES" >> $GITHUB_OUTPUT
        echo "has-errors=$HAS_ERRORS" >> $GITHUB_OUTPUT

        if [ "$HAS_ERRORS" = "true" ]; then
          exit 1
        fi
